apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: aaaaaa.agyo.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-service
                port:
                  number: 8080
#### Ketu kam krijuar nje A record qe ben point te ip e service loadbalancerit te nginx ingress controller. website hapet dhe mund ta shohesh aplikacioin running
